CREATE TABLE [dbo].[Funcionario]
(
	[Codigo] INT NOT NULL CONSTRAINT [PK FUNCIONARIO] PRIMARY KEY IDENTITY, 
    [Nome] VARCHAR(50) NOT NULL, 
    [Email] VARCHAR(50) NOT NULL CONSTRAINT [UN FUNCIONARIO_EMAIL] UNIQUE, 
    [Rg] VARCHAR(12) NOT NULL CONSTRAINT [UN FUNCIONARIO_RG] UNIQUE, 
    [Cpf] VARCHAR(14) NOT NULL CONSTRAINT [UN FUNCIONARIO_CPF] UNIQUE, 
    [Uf] VARCHAR(2) NOT NULL, 
    [Cep] VARCHAR(9) NOT NULL, 
    [Cidade] VARCHAR(50) NOT NULL, 
    [Bairro] VARCHAR(50) NOT NULL, 
    [Logradouro] VARCHAR(50) NOT NULL, 
    [Numero] VARCHAR(2) NOT NULL, 
    [Complemento] VARCHAR(50) NULL
)
