CREATE TABLE [dbo].[Venda]
(
	[Codigo] INT NOT NULL CONSTRAINT [PK VENDA] PRIMARY KEY IDENTITY, 
    [Cod_Funcionario] INT NOT NULL CONSTRAINT [FK VENDA / FUNCIONARIO] REFERENCES FUNCIONARIO(CODIGO), 
    [Cpf_Cliente] VARCHAR(14) NOT NULL CONSTRAINT [FK VENDA / CLIENTE] REFERENCES CLIENTE(CPF), 
    [Dt_Venda] DATE NOT NULL, 
    [Valor_Total] FLOAT NOT NULL
)
